# Generated by Django 4.1.1 on 2022-09-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='topping_1',
            field=models.IntegerField(choices=[(1, 'Pepperoni'), (2, 'Mushroom'), (3, 'Extra cheese'), (4, 'Sausage'), (5, 'Onion'), (6, 'Black olives'), (7, 'Green pepper'), (8, 'Fresh garlic'), (9, 'Tomato'), (10, 'Fresh basil')], default=1),
        ),
        migrations.AlterField(
            model_name='menu',
            name='topping_2',
            field=models.IntegerField(choices=[(1, 'Pepperoni'), (2, 'Mushroom'), (3, 'Extra cheese'), (4, 'Sausage'), (5, 'Onion'), (6, 'Black olives'), (7, 'Green pepper'), (8, 'Fresh garlic'), (9, 'Tomato'), (10, 'Fresh basil')], default=3),
        ),
        migrations.AlterField(
            model_name='menu',
            name='topping_3',
            field=models.IntegerField(choices=[(1, 'Pepperoni'), (2, 'Mushroom'), (3, 'Extra cheese'), (4, 'Sausage'), (5, 'Onion'), (6, 'Black olives'), (7, 'Green pepper'), (8, 'Fresh garlic'), (9, 'Tomato'), (10, 'Fresh basil')], default=6),
        ),
    ]
