# Generated by Django 4.1.1 on 2022-10-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_menu_topping_1_alter_menu_topping_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='picture',
            field=models.ImageField(default='pizza-images/ivan-torres-MQUqbmszGGM-unsplash.jpg', upload_to='pizza-images'),
        ),
    ]
