# Generated by Django 4.1.1 on 2022-10-17 01:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Preparing'), (2, 'In Route'), (3, 'Delivered')], default=1, max_length=10),
        ),
    ]
