# Generated by Django 4.1.1 on 2022-10-15 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('extras', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'French Fry'), (2, 'Coke'), (3, 'Sprite')], max_length=30)),
                ('delivery_status', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Preparing'), (2, 'In Route'), (3, 'Delivered')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
