# Generated by Django 4.1.1 on 2022-10-15 03:05

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account_api', '0003_alter_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='extras',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'None'), (2, 'French Fry'), (3, 'Coke'), (4, 'Sprite')], max_length=30),
        ),
    ]
