# Generated by Django 4.1.1 on 2022-10-15 03:08

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account_api', '0004_alter_order_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Preparing'), (2, 'In Route'), (3, 'Delivered')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='extras',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'French Fry'), (2, 'Coke'), (3, 'Sprite')], max_length=30),
        ),
    ]
